Ext.define('Ilc.resources.Resources', {
    singleton: true,
    
    locale: 'ro-RO',

    resources: {
        'mainMenu.tasks': 'Sarcini',
        'mainMenu.trainings': 'Instruiri',
        'mainMenu.customers': 'Clienti',
        'mainMenu.students': 'Studenti',
        'mainMenu.statistics': 'Statistici',
        'mainMenu.trainers': 'Profesori',

        'common.name': 'Nume',
        'common.status': 'Status',
        'common.execute': 'Executa',
        'common.trainer': 'Profesor',
        'common.customer': 'Client',
        'common.subject': 'Subiect',
        'common.owners': 'Proprietari',
        'common.newTraining': 'Instruire noua',
        'common.contact': 'Contact',
        'common.bankAccount': 'Cont bancar',
        'common.newCustomer': 'Client nou',
        'common.edit': 'Editeaza',
        'common.delete': 'Sterge',
        'common.newStudent': 'Student nou',
        'common.phone': 'Telefon',
        'common.newTrainer': 'Profesor nou',
        'common.possibleCosts': 'Costuri posibile',
        'common.lessonNo': 'Nr. de lectii',
        'common.lessonDuration': 'Durata lectie',
        'common.interviewDay': 'Ziua interviului',
        'common.location': 'Locatie',
        'common.createInterview': 'Creeaza interviu',
        'common.studentsInterviews': 'Interviuri studenti',
        'common.view': 'Vezi',
        'common.add': 'Adauga',
        'common.close': 'Inchide',
        'common.done': 'Facut',
        'common.lessons': 'Lectii',
        'common.evaluations': 'Evaluari',
        'common.progress': 'Progres',
        'common.exam': 'Examen',
        'common.trainingEval': 'Evaluare instruire',
        'common.planInterview': 'Planuieste interviu',
        'common.interview': 'Interviu',
        'common.newInterview': 'Interviu nou',
        'common.listeningLevel': 'Nivel ascultare',
        'common.listeningTargetLevel': 'Nivel tinta ascultare',
        'common.planLessons': 'Planuieste lectii',
        'common.progressEvaluations': 'Evaluari progres',
        'common.startDate': 'Data inceput',
        'common.endDate': 'Data incheiere',
        'common.system': 'Sistem',
        'common.students': 'Studenti',
        'common.billingAddress': 'Adresa facturare',
        'common.contactName': 'Nume contact',
        'common.contactEmail': 'Email contact',
        'common.phoneNr': 'Telefon',
        'common.address': 'Adresa',
        'common.student': 'Student',
        'common.createOffer': 'Creeaza oferta',

        'formats.date': 'MM-DD-YYYY HH:mm',
        'formats.extjsdate': 'm-d-Y g:i'
    }
});