Ext.define('Ilc.resources.Resources', {
    singleton: true,

    resources: {
        'mainMenu.tasks': '',
        'mainMenu.trainings': '',
        'mainMenu.customers': '',
        'mainMenu.students': '',
        'mainMenu.statistics': '',
        'mainMenu.trainers': '',

        'common.name': '',
        'common.status': '',
        'common.execute': '',
        'common.trainer': '',
        'common.customer': '',
        'common.subject': '',
        'common.owners': '',
        'common.newTraining': '',
        'common.contact': '',
        'common.bankAccount': '',
        'common.newCustomer': '',
        'common.edit': '',
        'common.delete': '',
        'common.newStudent': '',
        'common.phone': '',
        'common.newTrainer': '',
        'common.possibleCosts': '',
        'common.lessonNo': '',
        'common.lessonDuration': '',
        'common.interviewDay': '',
        'common.location': '',
        'common.createInterview': '',
        'common.studentsInterviews': '',
        'common.view': '',
        'common.add': '',
        'common.close': '',
        'common.done': '',
        'common.lessons': '',
        'common.evaluations': '',
        'common.progress': '',
        'common.exam': '',
        'common.trainingEval': '',
        'common.planInterview': '',
        'common.interview': '',
        'common.newInterview': '',
        'common.listeningLevel': '',
        'common.listeningTargetLevel': '',
        'common.planLessons': '',
        'common.progressEvaluations': '',
        'common.startDate': '',
        'common.endDate': '',
        'common.system': '',
        'common.students': '',
        'common.billingAddress': '',
        'common.contactName': '',
        'common.contactEmail': '',
        'common.phoneNr': '',
        'common.address': '',
        'common.student': '',
        'common.createOffer': '',

        'formats.date': 'MM-DD-YYYY HH:mm',
        'formats.extjsdate': 'm-d-Y g:i'
    }
});