Ext.define('Ilc.resources.Resources', {
    singleton: true,
    
    locale: 'en-GB',

    resources: {
        'mainMenu.tasks': 'Tasks',
        'mainMenu.trainings': 'Trainings',
        'mainMenu.customers': 'Customers',
        'mainMenu.students': 'Students',
        'mainMenu.statistics': 'Statistics',
        'mainMenu.trainers': 'Trainers',
        'mainMenu.users': 'Users',
        'mainMenu.roles': 'Roles',
        'mainMenu.subjects': 'Subjects',
        'mainMenu.settings': 'Settings',
        'mainMenu.planning': 'Planning',
        
        'common.trainingId': 'Training Id',
        'common.id': 'Id',
        'common.name': 'Name',
        'common.status': 'Status',
        'common.execute': 'Execute',
        'common.trainer': 'Trainer',
        'common.customer': 'Customer',
        'common.subject': 'Subject',
        'common.owners': 'Owners',
        'common.newTraining': 'New training',
        'common.contact': 'Contact',
        'common.bankAccount': 'Bank account',
        'common.newCustomer': 'New customer',
        'common.edit': 'Edit',
        'common.delete': 'Delete',
        'common.newStudent': 'New Student',
        'common.phone': 'Phone',
        'common.newTrainer': 'New trainer',
        'common.possibleCosts': 'Possible costs',
        'common.lessonNo': 'No. of lessons',
        'common.lessonDuration': 'Lesson duration',
        'common.interviewDay': 'Interview Day',
        'common.location': 'Location',
        'common.createInterview': 'Create interview',
        'common.studentsInterviews': 'Students interviews',
        'common.view': 'View',
        'common.add': 'Add',
        'common.close': 'Close',
        'common.done': 'Done',
        'common.lessons': 'Lessons',
        'common.evaluations': 'Evaluations',
        'common.progress': 'Progress',
        'common.exam': 'Exam',
        'common.trainingEval': 'Training evaluation',
        'common.planInterview': 'Plan interview',
        'common.interview': 'Interview',
        'common.newInterview': 'Enter interview findings',
        'common.listeningLevel': 'Listening level',
        'common.listeningTargetLevel': 'Listening target level',
        'common.planLessons': 'Plan lessons',
        'common.progressEvaluations': 'Progress evaluations',
        'common.startDate': 'Start date',
        'common.endDate': 'End date',
        'common.system': 'System',
        'common.students': 'Students',
        'common.billingAddress': 'Billing address',
        'common.contactName': 'Contact name',
        'common.contactEmail': 'Contact email',
        'common.phoneNr': 'Phone',
        'common.address': 'Address',
        'common.student': 'Student',
        'common.createOffer': 'Create offer',
        'common.file': 'File',
        'common.creator': 'Creator',
        'common.createAt': 'Created at',
        'common.planning': 'Planning',
        'common.readingLevel': 'Reading level',
        'common.readingTargetLevel': 'Reading target level',
        'common.interactiveTalkingLevel': 'Interactive talking level',        'common.interactiveTalkingDesiredLevel': 'Interactive talking target level',
        'common.productiveTalkingLevel': 'Productive talking level',
        'common.productiveTalkingTargetLevel': 'Productive talking target level',
        'common.writingLevel': 'Writing level',
        'common.writingTargetLevel': 'Writing target level',
        'common.accepted': 'Accepted',
        'common.rejected': 'Rejected',
        'common.newAssesment': 'New assesment',
        'common.listeningEntryLevel': 'Listening entry level',
        'common.listeningExitLevel': 'Listening exit level',
        'common.readingEntryLevel': 'Reading entry level',
        'common.readingExitLevel': 'Reading exit level',
        'common.interactiveTalkingEntryLevel': 'Interactive talking entry level',
        'common.interactiveTalkingExitLevel': 'Interactive talking exit level',
        'common.productiveTalkingEntryLevel': 'Productive talking entry level',
        'common.productiveTalkingExitLevel': 'Productive talking exit level',
        'common.writingEntryLevel': 'Writing entry level',
        'common.writingExitLevel': 'Writing exit level',
        'common.logout': 'Logout',
        'common.save': 'Save',
        'common.remarks': 'Remarks',
        'common.level': 'Level',
        'common.targetLevel': 'Target level',
        'common.listening': 'Listening',
        'common.reading': 'Reading',
        'common.interactiveTalking': 'Interactive talking',
        'common.productiveTalking': 'Productive talking',
        'common.writing': 'Writing',
        'common.cancel': 'Cancel',
        'common.update': 'Update',
        'common.username': 'Username',
        'common.newUser': 'New user',
        'common.createUser': 'Create User',
        'common.firstName': 'Firstname',
        'common.lastName': 'Lastname',
        'common.email': 'Email',
        'common.newSubject': 'New subject',

        'tasks.title.ended': 'Students assesments',
        'tasks.title.offer': 'Accept/reject the training offer',

        'tasks.offer.mainLbl': 'Please select the next status of the training to either accepted or rejected',

        'formats.date': 'MM-DD-YYYY HH:mm',
        'formats.extjsdate': 'm-d-Y g:i'
    }
});