Ext.define('Ilc.resources.Resources', {
    singleton: true,
    
    resources: {
        'mainMenu.tasks': 'Tasks',
        'mainMenu.trainings': 'Trainings',
        'mainMenu.customers': 'Customers',
        'mainMenu.students': 'Students',
        'mainMenu.statistics': 'Analytics',
        'mainMenu.trainers': 'Trainers',
        'mainMenu.users': 'Users',
        'mainMenu.roles': 'Roles',
        'mainMenu.subjects': 'Subjects',
        'mainMenu.settings': 'Settings',
        'mainMenu.planning': 'Planning',
        'mainMenu.companies': 'Companies',
        'mainMenu.login': 'Login',

        'common.trainingId': 'Training Id',
        'common.id': 'Id',
        'common.name': 'Name',
        'common.status': 'Status',
        'common.execute': 'Execute',
        'common.trainer': 'Trainer',
        'common.customer': 'Customer',
        'common.subject': 'Subject',
        'common.owners': 'Owners',
        'common.newTraining': 'New training',
        'common.contact': 'Contact',
        'common.bankAccount': 'Bank account',
        'common.bankName': 'Bank name',
        'common.postcode': 'Postcode',
        'common.customerId': 'Customer ID',

        'common.newCustomer': 'New customer',
        'common.edit': 'Edit',
        'common.delete': 'Delete',
        'common.newStudent': 'New Student',
        'common.phone': 'Phone',
        'common.newTrainer': 'New trainer',
        'common.possibleCosts': 'Possible costs',
        'common.lessonNo': 'No. of lessons',
        'common.lessonDuration': 'Lesson duration',
        'common.interviewDay': 'Interview Day',
        'common.location': 'Location',
        'common.createInterview': 'Create interview',
        'common.studentsInterviews': 'Students interviews',
        'common.view': 'View',
        'common.add': 'Add',
        'common.close': 'Close',
        'common.done': 'Done',
        'common.lessons': 'Lessons',
        'common.evaluations': 'Evaluations',
        'common.progress': 'Progress',
        'common.exam': 'Exam',
        'common.trainingEval': 'Training evaluation',
        'common.planInterview': 'Plan interview',
        'common.interview': 'Interview',
        'common.newInterview': 'Enter interview findings',
        'common.listeningLevel': 'Listening level',
        'common.listeningTargetLevel': 'Listening target level',
        'common.planLessons': 'Plan lessons',
        'common.progressEvaluations': 'Progress evaluations',
        'common.startDate': 'Start date',
        'common.endDate': 'End date',
        'common.system': 'System',
        'common.students': 'Students',
        'common.billingAddress': 'Address',
        'common.contactName': 'Contact name',
        'common.contactEmail': 'Contact email',
        'common.phoneNr': 'Phone',
        'common.address': 'Address',
        'common.student': 'Student',
        'common.createOffer': 'Create offer',
        'common.file': 'File',
        'common.creator': 'Creator',
        'common.createAt': 'Created at',
        'common.planning': 'Planning',
        'common.readingLevel': 'Reading level',
        'common.readingTargetLevel': 'Reading target level',
        'common.interactiveTalkingLevel': 'Interactive talking level',
        'common.interactiveTalkingDesiredLevel': 'Interactive talking target level',
        'common.productiveTalkingLevel': 'Productive talking level',
        'common.productiveTalkingTargetLevel': 'Productive talking target level',
        'common.writingLevel': 'Writing level',
        'common.writingTargetLevel': 'Writing target level',
        'common.accepted': 'Accepted',
        'common.rejected': 'Rejected',
        'common.newAssesment': 'New assesment',
        'common.listeningEntryLevel': 'Listening entry level',
        'common.listeningExitLevel': 'Listening exit level',
        'common.readingEntryLevel': 'Reading entry level',
        'common.readingExitLevel': 'Reading exit level',
        'common.interactiveTalkingEntryLevel': 'Interactive talking entry level',
        'common.interactiveTalkingExitLevel': 'Interactive talking exit level',
        'common.productiveTalkingEntryLevel': 'Productive talking entry level',
        'common.productiveTalkingExitLevel': 'Productive talking exit level',
        'common.writingEntryLevel': 'Writing entry level',
        'common.writingExitLevel': 'Writing exit level',
        'common.logout': 'Logout',
        'common.save': 'Save',
        'common.remarks': 'Remarks',
        'common.level': 'Level',
        'common.targetLevel': 'Target level',
        'common.listening': 'Listening',
        'common.reading': 'Reading',
        'common.interactiveTalking': 'Interactive talking',
        'common.productiveTalking': 'Productive talking',
        'common.writing': 'Writing',
        'common.cancel': 'Cancel',
        'common.update': 'Update',
        'common.username': 'Username',
        'common.newUser': 'New user',
        'common.createUser': 'Create User',
        'common.firstName': 'Firstname',
        'common.lastName': 'Lastname',
        'common.email': 'Email',
        'common.newSubject': 'New subject',
        'common.yes': 'Yes',
        'common.no': 'No',
        'common.main': 'Main',
        'common.trainingContact': 'Training contact',
        'common.price': 'Price',
        'common.subjects': 'Subjects',
        'common.spendings': 'Spendings',
        'common.newTemplate': 'New Template',
        'common.avatar': 'Avatar',
        'common.gender': 'Gender',
        'common.dateOfBirth': 'Date of birth',
        'common.newCompany': 'New company',
        'common.publish': 'Publish',
        'common.validate': 'Validate',
        'common.join': 'Join',
        'common.actions': 'Actions',
        'common.profile': 'Profile',
        'common.currentPassword': 'Current password',
        'common.newPassword': 'New password',
        'common.password': 'Password',
        'common.company': 'Company',
        'common.shiftTemplates': 'Shift templates',
        'common.friendlyName': 'Friendly name',
        'common.claims': 'Capabilities',
        'common.back': 'Back',
        'common.type': 'Type',
        'common.skip': 'Skip',
        'common.details': 'Details',
      
        'common.address': 'Address',
        'common.city': 'City',
        'common.country': 'Country',
        'common.active': 'Active',
        'common.createDate': 'Creation date',
        'common.trainings': 'Trainings',
        'common.amount': 'Amount',
        'common.sentAt': 'Sent Date',
        'common.paymentDueAt': 'Due Date',
        'common.tos': 'Terms and Conditions',
        'common.payed': 'Paid',
        'common.notSent':'Not sent',
        'common.trainingMaterial': 'Training material',

        'common.addStudent': 'Add student',
        'common.addContact': 'Add contact',
        'common.addExpense' : 'Add expense',

        'common.fiscalCode': 'VAT number',
        'common.commerceNumber': 'Chamber of commerce',
        'common.addCustomerContact' : 'Add customer contact person',
        'common.newCustomerContact': 'New customer contact',

        'common.addAction': 'Add action',

        'common.customerRelationship': 'Customer relationship',
        'common.customerContacts': 'Customer contacts',
        'common.general' : 'General',
        'common.color': 'Color',


        'tasks.title.ended': 'Students assesments',
        'tasks.title.offer': 'Accept/reject the training offer',
        'tasks.planned.mainLbl': 'Ready to start the training?',

        'tasks.offer.mainLbl': 'Please select the next status of the training to either accepted or rejected',

        'statistics.priceSpendings': 'Price / Spendings',
        'statistics.customerPurchases': 'Customer purchases',
        'statistics.trainingsMonth': 'Trainings / Month',

        'view.trainings.create.title': 'New training',
        
        'view.roles.create.title': 'New role',

        'view.subjects.create.title': 'New subject',

        'formats.date': 'MM-DD-YYYY',
        'formats.extjsdate': 'm-d-Y g:i',
        'formats.extjsdateonly': 'm-d-Y'
    }
});