Ext.define('Ilc.resources.Resources', {
    singleton: true,

    resources: {
        'mainMenu.tasks': 'Tasks',
        'mainMenu.trainings': 'Trainings',
        'mainMenu.customers': 'Clienți',
        'mainMenu.students': 'Participanți',
        'mainMenu.statistics': 'Statistici',
        'mainMenu.trainers': 'Trainers',
        'mainMenu.users': 'Utilizatori',
        'mainMenu.roles': 'Roluri',
        'mainMenu.subjects': 'Cursuri',
        'mainMenu.settings': 'Setări',
        'mainMenu.planning': 'Planificare',

        'common.roles': 'Roluri',
        'common.users': 'Utilizatori',
        'common.statusDefinitions': 'Definitie stari',
        'common.gradingSystems': 'Sistem notare',
        'common.importTrainers': 'Import traineri',
        'common.importStudents': 'Import participanti',
        'common.importCustomers': 'Import clienti',
        'common.documentTemplates': 'Sablon documente',
        'common.expenseTypes': 'Tipuri cheltuieli',

        'common.trainingId': 'Id curs',
        'common.id': 'Id',
        'common.name': 'Nume',
        'common.status': 'Stare',
        'common.execute': 'Execută',
        'common.trainer': 'Trainer',
        'common.customer': 'Client',
        'common.subject': 'Curs',
        'common.owners': 'Responsabil',
        'common.newTraining': 'Training nou',
        'common.contact': 'Contact',
        'common.bankAccount': 'Cont bancar',
        'common.newCustomer': 'Client nou',
        'common.edit': 'Modifică',
        'common.delete': 'Șterge',
        'common.newStudent': 'Participant nou',
        'common.phone': 'Telefon',
        'common.newTrainer': 'Profesor nou',
        'common.possibleCosts': 'Costuri posibile',
        'common.lessonNo': 'Numar de lecții',
        'common.lessonDuration': 'Durata lecției',
        'common.interviewDay': 'Dată interviu',
        'common.location': 'Locația',
        'common.createInterview': 'Planifică interviu',
        'common.studentsInterviews': 'Interviu participanți',
        'common.view': 'Vedere',
        'common.add': 'Adaugă',
        'common.close': 'Închide',
        'common.done': 'Termină',
        'common.lessons': 'Lecții',
        'common.evaluations': 'Evaluări',
        'common.progress': 'Progres',
        'common.exam': 'Examen',
        'common.trainingEval': 'Evaluare curs',
        'common.planInterview': 'Planifică interviu',
        'common.interview': 'Interviu',
        'common.newInterview': 'Adaugă rezultatele interviului',
        'common.listeningLevel': 'Nivel înțelegere',
        'common.listeningTargetLevel': 'Nivel înțelegere dorit',
        'common.planLessons': 'Planifică lecții',
        'common.progressEvaluations': 'Evaluare progres',
        'common.startDate': 'Data de început',
        'common.endDate': 'Data de sfarșit',
        'common.system': 'Sistem',
        'common.students': 'Participanți',
        'common.billingAddress': 'Adresă de facturare',
        'common.contactName': 'Nume contact',
        'common.contactEmail': 'Email contact',
        'common.phoneNr': 'Telefon',
        'common.address': 'Adresa',
        'common.student': 'Participant',
        'common.createOffer': 'Crează ofertă',
        'common.file': 'Fișier',
        'common.creator': 'Creator',
        'common.createAt': 'Creat la',
        'common.planning': 'Planificare',
        'common.readingLevel': 'Nivel citire',
        'common.readingTargetLevel': 'Nivel citire dorit',
        'common.interactiveTalkingLevel': 'Nivel conversatie',
        'common.interactiveTalkingDesiredLevel': 'Nivel conversatie dorit',
        'common.productiveTalkingLevel': 'Nivel conversarie productiva',
        'common.productiveTalkingTargetLevel': 'Nivel conversarie productiva dorit',
        'common.writingLevel': 'Nivel scris',
        'common.writingTargetLevel': 'Nivel scris dorit',
        'common.accepted': 'Acceptat',
        'common.rejected': 'Refuzat',
        'common.newAssesment': 'Evaluare noua',
        'common.listeningEntryLevel': 'Nivel înțelegere',
        'common.listeningExitLevel': 'Nivel înțelegere dorit',
        'common.readingEntryLevel': 'Nivel citire',
        'common.readingExitLevel': 'Nivel citire dorit',
        'common.interactiveTalkingEntryLevel': 'Interactive talking entry level',
        'common.interactiveTalkingExitLevel': 'Interactive talking exit level',
        'common.productiveTalkingEntryLevel': 'Productive talking entry level',
        'common.productiveTalkingExitLevel': 'Productive talking exit level',
        'common.writingEntryLevel': 'Writing entry level',
        'common.writingExitLevel': 'Writing exit level',
        'common.logout': 'Ieșire',
        'common.save': 'Salvează',
        'common.remarks': 'Remarci',
        'common.level': 'Nivel',
        'common.targetLevel': 'Nivel dorit',
        'common.listening': 'Înțelegere',
        'common.reading': 'Citire',
        'common.interactiveTalking': 'Conversatie productiva',
        'common.productiveTalking': 'Conversatie productiva',
        'common.writing': 'citire',
        'common.cancel': 'Renunță',
        'common.update': 'Modifică',
        'common.username': 'Nume utilizator',
        'common.newUser': 'Utilizator nou',
        'common.createUser': 'Creaza utilizator',
        'common.firstName': 'Prenume',
        'common.lastName': 'Nume',
        'common.email': 'Email',
        'common.newSubject': 'Curs nou',
        'common.yes': 'da',
        'common.no': 'nu',
        'common.main': 'Principal',
        'common.trainingContact': 'Contact curs',
        'common.price': 'Preț',
        'common.subjects': 'Cursuri',
		
		'common.customerId': 'ID client',
		'common.bankName': 'Nume bancă',
		'common.phoneContact': 'Telefon persoana contact',
		
		


        'common.newTemplate': 'Șablon nou',
        'common.avatar': 'Avatar',
        'common.gender': 'Sex',
        'common.dateOfBirth': 'Data nașterii',
        'common.newCompany': 'Companie nouă',
        'common.publish': 'Publică',
        'common.validate': 'Validează',
        'common.join': 'Alătură',
        'common.actions': 'Acțiuni',
        'common.profile': 'Profil',
        'common.currentPassword': 'Parola curentă',
        'common.newPassword': 'Noua parolă',
        'common.password': 'Parola',
        'common.company': 'Compania',
        'common.shiftTemplates': 'Șablon de disponibilitate',
        'common.friendlyName': 'Nume alternativ',
        'common.claims': 'Capabilities',
        'common.back': 'Înapoi',
        'common.type': 'Tip',
        'common.skip': 'Sări peste',
        'common.details': 'Detalii',

        'common.city': 'Orașul',
        'common.country': 'Țara',
        'common.active': 'Activ',
        'common.createDate': 'Data creerii',
        'common.trainings': 'Trainings',
        'common.amount': 'Sumă',
        'common.sentAt': 'Data trimiterii',
        'common.paymentDueAt': 'Data limită de plată',
        'common.tos': 'Termene și condiții',
        'common.payed': 'Platită',
        'common.notSent': 'Netrimisă',
        'common.trainingMaterial': 'Materiale de training',

        'common.addStudent': 'Adaugă participant',
        'common.addContact': 'Adaugă personă de contact',
        'common.addExpense': 'Adaugă cheltuială',

        'common.fiscalCode': 'Număr TVA',
        'common.commerceNumber': 'Camera de comerț',
        'common.addCustomerContact': 'Adaugă persoană de contact',
        'common.newCustomerContact': 'Adaugă persoană de contact client',

        'common.addAction': 'Adaugă acțiune',

        'common.customerRelationship': 'Relații cu clienții',
        'common.customerContacts': 'Contact client',
        'common.general': 'General',
        'common.spendings': 'Cheltuieli',
        'common.color': 'Culoare',
        'common.stakeholders': 'Contributori',
        'common.newShiftTemplate' : 'Nou șablon disponibilitate',


        'tasks.title.ended': 'Evaluări participanți',
        'tasks.title.offer': 'Acceptă/refuză oferta',
        'tasks.planned.mainLbl': 'Gata pentru începerea training-ului?',

        'statistics.priceSpendings': 'Treț / Cheltuieli',
        'statistics.customerPurchases': 'Traininguri vândute / Client',
        'statistics.trainingsMonth': 'Traininguri vândute / Lună',

        'view.trainings.create.title': 'Training nou',

        'view.roles.create.title': 'Rol nou',

        'view.subjects.create.title': 'Curs nou',

        'tasks.offer.mainLbl': 'Selecteaza noua stare a cursului: acceptat/refuzat',



        'formats.date': 'MM-DD-YYYY',
        'formats.extjsdate': 'm-d-Y g:i',
        'formats.extjsdateonly': 'm-d-Y'
    }
});