Ext.define('Ilc.resources.Resources', {
    singleton: true,
    
    locale: 'en-GB',

    resources: {
        'mainMenu.tasks': 'Tasks',
        'mainMenu.trainings': 'Trainings',
        'mainMenu.customers': 'Customers',
        'mainMenu.students': 'Students',
        'mainMenu.statistics': 'Statistics',
        'mainMenu.trainers': 'Trainers',

        'common.name': 'Name',
        'common.status': 'Status',
        'common.execute': 'Execute',
        'common.trainer': 'Trainer',
        'common.customer': 'Customer',
        'common.subject': 'Subject',
        'common.owners': 'Owners',
        'common.newTraining': 'New training',
        'common.contact': 'Contact',
        'common.bankAccount': 'Bank account',
        'common.newCustomer': 'New customer',
        'common.edit': 'Edit',
        'common.delete': 'Delete',
        'common.newStudent': 'New Student',
        'common.phone': 'Phone',
        'common.newTrainer': 'New trainer',
        'common.possibleCosts': 'Possible costs',
        'common.lessonNo': 'No. of lessons',
        'common.lessonDuration': 'Lesson duration',
        'common.interviewDay': 'Interview Day',
        'common.location': 'Location',
        'common.createInterview': 'Create interview',
        'common.studentsInterviews': 'Students interviews',
        'common.view': 'View',
        'common.add': 'Add',
        'common.close': 'Close',
        'common.done': 'Done',
        'common.lessons': 'Lessons',
        'common.evaluations': 'Evaluations',
        'common.progress': 'Progress',
        'common.exam': 'Exam',
        'common.trainingEval': 'Training evaluation',

        'formats.date': 'MM-DD-YYYY HH:mm',
    }
});