Ext.define('Ilc.resources.Resources', {
    singleton: true,

    resources: {
        'mainMenu.tasks': 'Tasks',
        'mainMenu.trainings': 'Cursuri',
        'mainMenu.customers': 'Clienti',
        'mainMenu.students': 'Studenti',
        'mainMenu.statistics': 'Raportari',
        'mainMenu.trainers': 'Profesori',
        'mainMenu.users': 'Utilizatori',
        'mainMenu.roles': 'Roluri',
        'mainMenu.subjects': 'Materii',
        'mainMenu.settings': 'Setari',
        'mainMenu.planning': 'Planificare',

        'common.trainingId': 'Id curs',
        'common.id': 'Id',
        'common.name': 'Nume',
        'common.status': 'Stare',
        'common.execute': 'Executa',
        'common.trainer': 'Profesor',
        'common.customer': 'Client',
        'common.subject': 'Materie',
        'common.owners': 'Responsabil',
        'common.newTraining': 'Training nou',
        'common.contact': 'Contact',
        'common.bankAccount': 'Cont bancar',
        'common.newCustomer': 'Client nou',
        'common.edit': 'Modifica',
        'common.delete': 'Sterge',
        'common.newStudent': 'Student nou',
        'common.phone': 'Telefon',
        'common.newTrainer': 'Profesor nou',
        'common.possibleCosts': 'Costuri posibile',
        'common.lessonNo': 'Numar de lectii',
        'common.lessonDuration': 'Durata lectiei',
        'common.interviewDay': 'Data interviu',
        'common.location': 'Locatia',
        'common.createInterview': 'Planifica interviu',
        'common.studentsInterviews': 'Interviui studenti',
        'common.view': 'Vedere',
        'common.add': 'Adauga',
        'common.close': 'Inchide',
        'common.done': 'Terminare',
        'common.lessons': 'Lectii',
        'common.evaluations': 'Evaluari',
        'common.progress': 'Progres',
        'common.exam': 'Examen',
        'common.trainingEval': 'Evaluare curs',
        'common.planInterview': 'Planifica interviu',
        'common.interview': 'Interviu',
        'common.newInterview': 'Adauga rezultatele interviului',
        'common.listeningLevel': 'Nivel ascultare',
        'common.listeningTargetLevel': 'Nivel ascultare dorit',
        'common.planLessons': 'Planifica lectii',
        'common.progressEvaluations': 'Evaluare progres',
        'common.startDate': 'Data start',
        'common.endDate': 'Data sfarsit',
        'common.system': 'Sistem',
        'common.students': 'Studenti',
        'common.billingAddress': 'Adresa facturare',
        'common.contactName': 'Nume contact',
        'common.contactEmail': 'Email contact',
        'common.phoneNr': 'Telefon',
        'common.address': 'Addresa',
        'common.student': 'Student',
        'common.createOffer': 'Creaza oferta',
        'common.file': 'Fisier',
        'common.creator': 'Creator',
        'common.createAt': 'Creat la',
        'common.planning': 'Planificare',
        'common.readingLevel': 'Nivel citire',
        'common.readingTargetLevel': 'Nivel citire dorit',
        'common.interactiveTalkingLevel': 'Nivel conversatie',
        'common.interactiveTalkingDesiredLevel': 'Nivel conversatie dorit',
        'common.productiveTalkingLevel': 'Nivel conversarie productiva',
        'common.productiveTalkingTargetLevel': 'Nivel conversarie productiva dorit',
        'common.writingLevel': 'Nivel scris',
        'common.writingTargetLevel': 'Nivel scris dorit',
        'common.accepted': 'Acceptat',
        'common.rejected': 'Refuzat',
        'common.newAssesment': 'Evaluare noua',
        'common.listeningEntryLevel': 'Nivel intelegere',
        'common.listeningExitLevel': 'Nivel intelegere dorit',
        'common.readingEntryLevel': 'Nivel citire',
        'common.readingExitLevel': 'Nivel citire dorit',
        'common.interactiveTalkingEntryLevel': 'Interactive talking entry level',
        'common.interactiveTalkingExitLevel': 'Interactive talking exit level',
        'common.productiveTalkingEntryLevel': 'Productive talking entry level',
        'common.productiveTalkingExitLevel': 'Productive talking exit level',
        'common.writingEntryLevel': 'Writing entry level',
        'common.writingExitLevel': 'Writing exit level',
        'common.logout': 'Iesire',
        'common.save': 'Salvare',
        'common.remarks': 'Remarci',
        'common.level': 'Nivel',
        'common.targetLevel': 'Nivel dorit',
        'common.listening': 'Intelegere',
        'common.reading': 'Citire',
        'common.interactiveTalking': 'Conversatie productiva',
        'common.productiveTalking': 'Conversatie productiva',
        'common.writing': 'citire',
        'common.cancel': 'Renunta',
        'common.update': 'Modificare',
        'common.username': 'Nuume utilizator',
        'common.newUser': 'User nou',
        'common.createUser': '',
        'common.firstName': 'Prenume',
        'common.lastName': 'Nume',
        'common.email': 'Email',
        'common.newSubject': 'New subject',
        'common.yes': 'da',
        'common.no': 'nu',
        'common.main': 'Principal',
        'common.trainingContact': 'Contact curs',
        'common.price': 'Pret',
        'common.subjects': 'Subiect',
        'common.spendings': 'Cheltuieli',

        'tasks.title.ended': 'Evaluare student',
        'tasks.title.offer': 'Accepta/refuza oferta de training',
        'tasks.planned.mainLbl': 'Gata de start pentu training?',

        'tasks.offer.mainLbl': 'Selecteaza noua stare a cursului: acceptat/refuzat',

        'statistics.priceSpendings': 'Pret/ Spendings',
        'statistics.customerPurchases': 'Cursuri clienti',
        'statistics.trainingsMonth': 'Cursuri / luna',

        'formats.date': 'MM-DD-YYYY HH:mm',
        'formats.extjsdate': 'm-d-Y g:i'
    }
});