// <auto-generated />
namespace Ilc.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class TrainerAvailability : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TrainerAvailability));
        
        string IMigrationMetadata.Id
        {
            get { return "201312201144080_TrainerAvailability"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
