// <auto-generated />
namespace Ilc.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RoleFlagToPreventDeletion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RoleFlagToPreventDeletion));
        
        string IMigrationMetadata.Id
        {
            get { return "201310220815345_RoleFlagToPreventDeletion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
