// <auto-generated />
namespace Ilc.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class TrainingInterviewsAndSchedule : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TrainingInterviewsAndSchedule));
        
        string IMigrationMetadata.Id
        {
            get { return "201308211249277_TrainingInterviewsAndSchedule"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
