// <auto-generated />
namespace Ilc.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class TrainingSpendings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TrainingSpendings));
        
        string IMigrationMetadata.Id
        {
            get { return "201311201230186_TrainingSpendings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
